#!/bin/bash

function help() {
    echo
    echo "$1 <command> [options]"
    echo
    echo "commands:"
    echo
    column -t -s"|" ./task.md | tail -n +3
    echo
}

# Set default env vars
DEFAULT_SITE=pgsql.localhost
GIT_BRANCH=$(git branch --show-current)
if [ ! -f .env ]; then
    export $(cat .env | sed 's/#.*//g' | xargs)
fi


function activate-venv() {
    source "venv$GIT_BRANCH/bin/activate"
}

function init-venv() {
    if [ ! -d "venv$GIT_BRANCH" ]; then
        python3 -m venv "venv$GIT_BRANCH"
        source "venv$GIT_BRANCH/bin/activate"
    fi
}

function install() {

    echo "Run native installation"

    # Init Python and install bench
    init-venv
    activate-venv
    pip install frappe-bench

    # Install Frappe with bench
    bench init --skip-redis-config-generation --frappe-branch version-13 frappe-bench

    # Set configuration
    cd frappe-bench
    bench set-mariadb-host localhost
    bench set-redis-cache-host localhost:6379
    bench set-redis-queue-host localhost:6380
    bench set-redis-socketio-host localhost:6381

    # Install site
    echo "Use 'frappe' for username and for password on prompts:"
    bench new-site $DEFAULT_SITE --db-type postgres --db-host localhost --db-password frappe --admin-password frappe

    # Enable developer mode
    bench --site $DEFAULT_SITE set-config developer_mode 1
    bench --site $DEFAULT_SITE set-config max_file_size 1000000
    bench --site $DEFAULT_SITE clear-cache
}

function docker-install() {

    echo "Run docker installation"
    docker exec -w /workspace frappe bench init --skip-redis-config-generation --frappe-branch version-13 frappe-bench
    docker_exec="docker exec -w /workspace/frappe-bench frappe"
    $docker_exec bench set-mariadb-host postgresql
    $docker_exec bench set-redis-cache-host redis-cache:6379
    $docker_exec bench set-redis-cache-host edis-queue:6379
    $docker_exec bench set-redis-cache-host redis-socketio:6379

    # Install site
    echo "Use 'frappe' for username and for password on prompts:"
    docker exec -w /workspace/frappe-bench -it frappe bench new-site $DEFAULT_SITE --db-type postgres --db-host postgresql

    # Enable developer mode
    $docker_exec bench --site $DEFAULT_SITE set-config developer_mode 1
    $docker_exec bench --site $DEFAULT_SITE set-config max_file_size 1000000
    $docker_exec bench --site $DEFAULT_SITE clear-cache
}

function native-bench() {
    init-venv
    activate-venv
    cd frappe-bench

    bench --site $DEFAULT_SITE "$@"
}

function docker-bench() {

    docker exec -w /workspace/frappe-bench frappe bench --site $DEFAULT_SITE "$@"
}

function version() {
    printf "\ndocker:\n"
    docker version
    printf "\ndocker-compose:\n"
    docker-compose version
    printf "\nwkhtmltopdf:\n"
    wkhtmltopdf --version
    printf "\npython:\n"
    python --version
    printf "\npip:\n"
    pip --version
    printf "\nnode:\n"
    node --version
    printf "\nnpm:\n"
    npm --version
    printf "\nyarn:\n"
    yarn --version
}

function new-app() {
    if test -z "$1"; then echo "\$1 is empty"; exit; fi

    activate-venv
    cd frappe-bench
    bench new-app $1
    bench --site $DEFAULT_SITE install-app $1
}

function get-app() {
    if test -z "$1"; then echo "\$1 is empty"; exit; fi
    if test -z "$2"; then echo "\$1 is empty"; exit; fi
    
    activate-venv
    cd frappe-bench
    bench get-app schools $1 $2
    bench --site $DEFAULT_SITE install-app $1
}

function install-app() {
    if test -z "$1"; then echo "\$1 is empty"; exit; fi
    
    activate-venv
    cd frappe-bench
    bench --site $DEFAULT_SITE install-app $1
}


function uninstall-app() {
    if test -z "$1"; then echo "\$1 is empty"; exit; fi
    
    activate-venv
    cd frappe-bench
    bench --site $DEFAULT_SITE uninstall-app $1
}

function clear-cache() {
    activate-venv
    cd frappe-bench
    bench --site all clear-cache
}

function start() {
    if [ "$1" = "native" ]; then
        activate-venv
        cd frappe-bench
        echo "Open http://localhost:8000/ in your browser and login using 'Administrator:frappe'."
        bench start
    fi

    if [ "$1" = "db" ]; then
        docker-compose up -d redis-cache
        docker-compose up -d redis-queue
        docker-compose up -d redis-socketio
        docker-compose up -d postgresql
    fi

    if [ "$1" = "all" ]; then
        docker-compose up -d
    fi

    if [ "$1" = "docker" ]; then
        echo "Open http://localhost:8000/ in your browser and login using 'Administrator:frappe'."
        docker exec -w /workspace/frappe-bench frappe bench start
    fi
}

function stop() {
    if test -z "$1"; then echo "\$1 is empty"; exit; fi

    if [ "$1" = "docker" ]; then
        docker exec -w /workspace/frappe-bench frappe killall -s 9 python
    fi

    if [ "$1" = "all" ]; then
        docker-compose stop
    fi
}

function restart() {
    if test -z "$1"; then
        docker-compose restart
    fi
}

case "$1" in
version)
    version
    ;;
install)
    install $2
    ;;
docker-install)
    docker-install $2
    ;;
native-bench)
    native-bench "${@:2}"
    ;;
docker-bench)
    docker-bench "${@:2}"
    ;;
init)
    init $2
    ;;
start)
    start $2
    ;;
stop)
    stop $2
    ;;
new-app)
    new-app $2
    ;;
get-app)
    get-app $2 $3
    ;;
install-app)
    install-app $2
    ;;
uninstall-app)
    uninstall-app $2
    ;;
restart)
    restart $2
    ;;
kill)
    docker-compose down -v
    ;;
clear-cache)
    clear-cache
    ;;
*)
    help task
    exit 1
    ;;
esac
